# Generated by Django 4.2 on 2025-02-13 09:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FogServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_endpoint', models.CharField(max_length=255, unique=True, verbose_name='服务接口')),
                ('keywords', models.JSONField(default=list, verbose_name='关键词列表')),
                ('keyword_load', models.IntegerField(default=0, verbose_name='关键词总负载')),
                ('status', models.CharField(choices=[('online', '在线'), ('offline', '离线'), ('maintenance', '维护中')], default='offline', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '雾服务器',
                'verbose_name_plural': '雾服务器',
                'db_table': 'fog_servers',
                'ordering': ['-created_at'],
            },
        ),
    ]
