# Generated by Django 4.2 on 2025-03-11 06:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='STVQueryRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='请求ID')),
                ('sstp_request_id', models.CharField(help_text='关联的SSTP请求ID', max_length=64, verbose_name='SSTP请求ID')),
                ('time_span', models.IntegerField(help_text='查询的时间跨度限制(Ts)', verbose_name='时间跨度')),
                ('query_ranges', models.TextField(help_text='需要覆盖的查询范围列表(Rid)，JSON格式', verbose_name='查询范围')),
                ('candidate_trajectories', models.TextField(help_text='SSTP筛选出的候选轨迹数据，JSON格式', verbose_name='候选轨迹')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'STV查询请求',
                'verbose_name_plural': 'STV查询请求',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='STVQueryResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_trajectories', models.TextField(help_text='满足条件的轨迹ID列表，JSON格式', verbose_name='结果轨迹')),
                ('processing_time', models.FloatField(help_text='处理耗时(秒)', verbose_name='处理时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('query', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='stv.stvqueryrequest', verbose_name='查询请求')),
            ],
            options={
                'verbose_name': 'STV查询结果',
                'verbose_name_plural': 'STV查询结果',
                'ordering': ['-created_at'],
            },
        ),
    ]
