# Generated by Django 4.2 on 2025-02-13 13:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fog_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fogserver',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='fogserver',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fogserver',
            name='keyword_load',
            field=models.FloatField(default=0, help_text='关键词负载百分比'),
        ),
        migrations.AlterField(
            model_name='fogserver',
            name='keywords',
            field=models.TextField(blank=True, help_text='分配的关键词列表，以逗号分隔'),
        ),
        migrations.AlterField(
            model_name='fogserver',
            name='service_endpoint',
            field=models.URLField(help_text='服务器接口地址', max_length=255, unique=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AlterField(
            model_name='fogserver',
            name='status',
            field=models.CharField(choices=[('online', '在线'), ('offline', '离线'), ('maintenance', '维护中')], default='offline', help_text='服务器状态', max_length=20),
        ),
        migrations.AlterField(
            model_name='fogserver',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
