# Generated by Django 4.2 on 2025-02-05 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.CharField(db_index=True, max_length=100)),
                ('point_id', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('date', models.IntegerField()),
                ('time', models.IntegerField()),
                ('keyword', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'tracks_table',
                'ordering': ['track_id', 'point_id'],
                'unique_together': {('track_id', 'point_id')},
            },
        ),
    ]
