# Generated by Django 4.2 on 2025-03-02 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QueryRequest',
            fields=[
                ('rid', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='请求ID')),
                ('fog_id', models.IntegerField(verbose_name='雾服务器ID')),
                ('keyword', models.BinaryField(verbose_name='关键词')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('status', models.CharField(default='pending', max_length=20, verbose_name='状态')),
            ],
            options={
                'verbose_name': '查询请求',
                'verbose_name_plural': '查询请求',
            },
        ),
    ]
